# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    image: mysql:5.7.38
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql01
    env_file:
      - docker-compose.env
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ${data_dir}/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: trinity_master
    networks:
      - net-app

  authserver:
    image: trinitycore/trinitycore:3.3.5
    container_name: authserver01
    env_file:
      - docker-compose.env
    restart: always
    tty: true
    depends_on: 
      - mysql
    ports:
      - 3724:3724
    volumes:
      - ${config_dir}/trinitycore/authserver/conf:/home/circleci/project/bin/check_install/etc
      - ${log_dir}/authserver:/trinity/log
    healthcheck:
      test: ["CMD","nc","localhost","3724"]
      timeout: 20s
      retries: 10
      start_period: 20s
    networks:
      - net-app
    entrypoint: authserver

  worldserver:
    image: trinitycore/trinitycore:3.3.5
    container_name: worldserver01
    env_file:
      - docker-compose.env
    restart: always
    tty: true
    depends_on: 
      - mysql
    ports:
      - 8085:8085
    volumes:
      - ${config_dir}/trinitycore/worldserver/conf:/home/circleci/project/bin/check_install/etc
      - ${config_dir}/trinitycore//worldserver/TDB_full_world_335.23011_2023_01_16.sql:/home/circleci/TDB_full_world_335.23011_2023_01_16.sql
      - ${data_dir}/3.3.5a:/trinity/data
      - ${log_dir}/worldserver:/trinity/log
    healthcheck:
      test: ["CMD","nc","localhost","8085"]
      timeout: 20s
      retries: 10
      start_period: 20s
    networks:
      - net-app
    entrypoint: worldserver

  php:
    build:
      context: ${config_dir}/php
      dockerfile: Dockerfile
    image: php:7.4_wow
    container_name: php01
    env_file:
      - docker-compose.env
    restart: always
    depends_on:
    - mysql
    volumes:
    - ${config_dir}/php/conf.d/php.ini:/usr/local/etc/php/php.ini
    - ${data_dir}/WoWSimpleRegistration:/usr/share/nginx/html
    networks:
    - net-app

  nginx:
    image: nginx:1.23
    container_name: nginx01
    env_file:
      - docker-compose.env
    restart: always
    depends_on:
    - php
    ports:
     - 80:80
    volumes:
     - ${config_dir}/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
     - ${data_dir}/WoWSimpleRegistration:/usr/share/nginx/html
     - ${log_dir}/nginx:/var/log/nginx
    networks:
    - net-app
networks:
  net-app:
